### ISSUE TITLE
Too slow when there are many tests

### ISSUE THREAD

**Issue by logan-han** [buildkite-plugins/test-collector-buildkite-plugin#44]
We have 500+ tests for a project and this plugin seems like just post the junit file one by one, which takes sweet time.

Would be great if this plugin can support consolidation before posting.

We're currently using https://www.npmjs.com/package/junit-report-merger for that purpose FYI

**Comment by toote** [comment]
@logan-han while an interesting idea, we're trying to make this plugin as simple as possible. Consolidating report files would be outside of the scope unless it can be easily done with plain bash an standard command-line tools.

From your comment I assume that you are working around the issue you describe by merging report files using that tool. Is that correct?

**Comment by logan-han** [comment]
@toote Yes, we have a workaround in place.

I suppose something like parallel execution can mitigate the issue as well.

**Comment by pzeballos** [comment]
Hey folks! We discussed this issue with the TA team, and their take is that merging the files before uploading them to Test Analytics (as you are currently doing) is the best solution we can suggest at the moment. We don't have any plans to support this from the plugin at this stage because this is a rare case. 

Thanks for your feedback! 🙏🏻
